---
- name: Download Kafka 4.0.1
  hosts: 172.29.139.164
  become: yes
  vars:
    kafka_version: "4.1.1"
    scala_version: "2.13"
    kafka_user: samckp
    kafka_group: samckp
    kafka_install_dir: /home/kafka
    kafka_data_dir: /home/lib/kafka
    kafka_log_dir: /home/log/kafka

  tasks:

    - name: Create group
      group:
        name: "{{ kafka_group }}"
        state: present


    - name: Create User
      user:
        name: "{{ kafka_user }}"
        group: "{{ kafka_group }}"
        shell: /bin/bash
        createhome: yes
        state: present

    - name: create directory
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ kafka_user }}"
        group: "{{ kafka_group }}"
        mode: '0755'

      loop:
        - "{{ kafka_install_dir }}"
        - "{{ kafka_data_dir }}"
        - "{{ kafka_log_dir }}"

    - name: Check if Kafka archive already exists
      stat:
        path: "/home/kafka/kafka_{{ scala_version }}-{{ kafka_version }}.tgz"
      register: kafka_archive

    - name: Download Kafka 4.1.1
      get_url:
        url: "https://dlcdn.apache.org/kafka/{{ kafka_version }}/kafka_{{ scala_version }}-{{ kafka_version }}.tgz"
        dest: "/home/kafka/kafka_{{ scala_version }}-{{ kafka_version }}.tgz"
        mode: '0644'
      when: not kafka_archive.stat.exists

    - name: Skip download message
      debug:
        msg: "Kafka archive already exists, skipping download"
      when: kafka_archive.stat.exists


    - name: "Untar  kafka_{{ scala_version }}-{{ kafka_version }}.tgz "
      ansible.builtin.unarchive:
        src: "{{ kafka_install_dir }}/kafka_{{ scala_version }}-{{ kafka_version }}.tgz"
        dest: "{{ kafka_install_dir }}"
        remote_src: yes